Update Run_Adblock_Reject_JSON.yml
Signed-off-by: rentry00 <108783040+rentry00@users.noreply.github.com>

diff --git a/.github/workflows/Run_Adblock_Reject_JSON.yml b/.github/workflows/Run_Adblock_Reject_JSON.yml
--- a/.github/workflows/Run_Adblock_Reject_JSON.yml
+++ b/.github/workflows/Run_Adblock_Reject_JSON.yml
@@ -34,17 +34,17 @@ jobs:
 
     - name: Force Add and Commit JSON file  # 强制添加并提交 adblock_reject.json 文件
       run: |
-        git lfs track "adblock_reject.json"
-        git lfs add .gitattributes
-        git lfs config --global user.name 'github-actions'  # 配置提交用户名
-        git lfs config --global user.email 'github-actions@github.com'  # 配置提交邮箱
-        git lfs add -f adblock_reject.json  # 强制添加 adblock_reject.json 文件
-        git lfs commit -m 'Update adblock_reject.json' || git lfs commit --allow-empty -m 'Empty commit to force push'  # 提交更改，若无更改则提交空更改
+        git track "adblock_reject.json"
+        git add .gitattributes
+        git config --global user.name 'github-actions'  # 配置提交用户名
+        git config --global user.email 'github-actions@github.com'  # 配置提交邮箱
+        git add -f adblock_reject.json  # 强制添加 adblock_reject.json 文件
+        git commit -m 'Update adblock_reject.json' || git commit --allow-empty -m 'Empty commit to force push'  # 提交更改，若无更改则提交空更改
 
     - name: Retry Push JSON file  # 推送 adblock_reject.json 文件，失败时重试
       env:
         TOKEN: ${{ secrets.TOKEN }}  # 使用 GitHub 密钥进行身份验证
       run: |
         for i in {1..5}; do  # 尝试最多5次
-          git lfs push --force origin HEAD && exit 0 || (echo "Push failed, retrying in 10 seconds..." && sleep 10)
+          git push --force origin HEAD && exit 0 || (echo "Push failed, retrying in 10 seconds..." && sleep 10)
         done
